export const Permission = {
  STAFF_MANAGE: "staff.manage",
  STAFF_MANAGE_LIMITED: "staff.manage.limited",
  MEMBER_READ: "member.read",
  MEMBER_WRITE: "member.write",
  MEMBERSHIP_SELL: "membership.sell",
  PAYMENT_READ: "payment.read",
  PAYMENT_WRITE: "payment.write",
  ATTENDANCE_READ: "attendance.read",
  CHECK_IN: "checkin.create",
  LEAD_READ: "lead.read",
  LEAD_WRITE: "lead.write",
  LEAD_CONVERT: "lead.convert",
  NOTIFICATION_READ: "notification.read",
  NOTIFICATION_MANAGE: "notification.manage",
  REPORT_OPERATIONS_READ: "report.operations.read",
  REPORT_FINANCE_READ: "report.finance.read",
  FINANCE_READ: "finance.read",
  GYM_CONFIG: "gym.configure",
} as const;

export type PermissionName = (typeof Permission)[keyof typeof Permission];

export const RoleName = {
  OWNER: "Owner",
  MANAGER: "Manager",
  FRONT_DESK: "Front desk",
  TRAINER: "Trainer",
  ACCOUNTANT: "Accountant",
} as const;

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  [RoleName.OWNER]: Object.values(Permission),
  [RoleName.MANAGER]: [
    Permission.STAFF_MANAGE_LIMITED,
    Permission.MEMBER_READ,
    Permission.MEMBER_WRITE,
    Permission.MEMBERSHIP_SELL,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_WRITE,
    Permission.ATTENDANCE_READ,
    Permission.CHECK_IN,
    Permission.LEAD_READ,
    Permission.LEAD_WRITE,
    Permission.LEAD_CONVERT,
    Permission.NOTIFICATION_READ,
    Permission.NOTIFICATION_MANAGE,
    Permission.REPORT_OPERATIONS_READ,
    Permission.REPORT_FINANCE_READ,
    Permission.FINANCE_READ,
  ],
  [RoleName.FRONT_DESK]: [
    Permission.MEMBER_READ,
    Permission.MEMBER_WRITE,
    Permission.MEMBERSHIP_SELL,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_WRITE,
    Permission.ATTENDANCE_READ,
    Permission.CHECK_IN,
    Permission.LEAD_READ,
    Permission.LEAD_WRITE,
    Permission.LEAD_CONVERT,
    Permission.NOTIFICATION_READ,
    Permission.REPORT_OPERATIONS_READ,
  ],
  [RoleName.TRAINER]: [Permission.MEMBER_READ],
  [RoleName.ACCOUNTANT]: [
    Permission.MEMBER_READ,
    Permission.PAYMENT_READ,
    Permission.PAYMENT_WRITE,
    Permission.REPORT_FINANCE_READ,
    Permission.FINANCE_READ,
  ],
};
